FirstRazorApp/Pages/Employeers/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FirstRazorApp.AppRepository;
using FirstRazorApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FirstRazorApp.Pages.Employeers
{
    public class DeleteModel : PageModel
    {
        private readonly IEmpoyeeRepository _employeeRepository;

        public DeleteModel(IEmpoyeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }

        [BindProperty] 
        public Employee Employee { get; set; }


        public IActionResult OnGet(int id)
        {
            Employee = _employeeRepository.GetEmployee(id);

            if (Employee == null)
                return RedirectToPage("/NotFound");

            return Page();
        }

        public IActionResult OnPost()
        {
            Employee deletedEmployee = _employeeRepository.Delete(Employee.Id);

            if (deletedEmployee == null)
                return RedirectToPage("/NotFound");

            return RedirectToPage("Index");
        }
    }
}

FirstRazorApp/Pages/Employeers/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FirstRazorApp.AppRepository;
using FirstRazorApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FirstRazorApp.Pages.Employeers
{
    public class DetailsModel : PageModel
    {
        private readonly IEmpoyeeRepository _employeeRepository;

        public DetailsModel(IEmpoyeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }

        public Employee Employee { get; private set; }

        // Теперь метод возвращает результат обработки, поэтому меняем тип с void на IActionResult
        public IActionResult OnGet(int id)
        {
            Employee = _employeeRepository.GetEmployee(id);

            // Добавляем проверку на null и делаем обработчик исключения
            if (Employee == null)
            {
                // Если модель пустая, то возвращаем в ответ на GET запрос страницу НЕ НАЙДЕНО
                return RedirectToPage("/NotFound");
            }
            // В противном случаи, возвращаем страницу
            return Page();
        }
    }
}

FirstRazorApp/Pages/Employeers/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using FirstRazorApp.AppRepository;
using FirstRazorApp.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FirstRazorApp.Pages.Employeers
{
    public class EditModel : PageModel
    {
        private readonly IEmpoyeeRepository _empoyeeRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        // Подключаем наш репозиторий данных
        public EditModel(IEmpoyeeRepository empoyeeRepository, IWebHostEnvironment webHostEnvironment )
        {
            _empoyeeRepository = empoyeeRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        [BindProperty]
        public Employee Employee { get; set; }

        [BindProperty] 
        public IFormFile Photo { get; set; }

        [BindProperty] 
        public bool Notify { get; set; }

        public string Message { get; set; }

        public IActionResult OnGet(int? id)
        {

            if (id.HasValue)
                Employee = _empoyeeRepository.GetEmployee(id.Value);
            else 
                Employee = new Employee();

            if (Employee == null)
            {
                return RedirectToPage("/NotFound");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            // Проверяем модель на валидность
            if (ModelState.IsValid)
            {
                // Сохраняем изображение
                if (Photo != null)
                {
                    if (Employee.PotoPath != null)
                    {
                        string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", Employee.PotoPath);

                        if (Employee.PotoPath != "noimage.png")
                            System.IO.File.Delete(filePath);
                    }

                    Employee.PotoPath = ProcessUploadedFile();
                }

                if (Employee.Id > 0)
                    // Обноляем данные в базе
                    Employee = _empoyeeRepository.Update(Employee);
                else
                    // Добавляем данные в базу
                    Employee = _empoyeeRepository.Add(Employee);

                // Записываем сообщение в TemData
                TempData["SuccessMessage"] = $"Update {Employee.Name} success!";

                // Возвращаем представление Index
                return RedirectToPage("/Employeers/Index");
            }

            return Page();
        }

        // Создаём метод обработки загруженных изображений
        private string ProcessUploadedFile()
        {
            string uniqueFileName = null;

            if (Photo != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }

        // Создаём метод обработки формы уведомлений
        public void OnPostUpdateNotificationPreferences(int id)
        {
            if (Notify)
            {
                Message = "Thank you for turning on notifications";
            }
            else
            {
                Message = "You have turned off email notifications";
            }

            Employee = _empoyeeRepository.GetEmployee(id);
        }
    }
}

FirstRazorApp/Pages/Employeers/EmpCount.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FirstRazorApp.Pages.Employeers
{
    public class EmpCountModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

FirstRazorApp/Pages/Employeers/Index.cshtml.cs
using System.Collections.Generic;
using FirstRazorApp.AppRepository;
using FirstRazorApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FirstRazorApp.Pages.Employeers
{
    public class IndexModel : PageModel
    {
        private readonly IEmpoyeeRepository employeeRepository;
        public IEnumerable<Employee> Employees { get; set; }
        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }
        public IndexModel(IEmpoyeeRepository _employeeRepository)
        {
            employeeRepository = _employeeRepository;
        }

        public void OnGet()
        {
            //Employees = employeeRepository.GetAllEmployees();
            Employees = employeeRepository.Search(SearchTerm);
        }
    }
}

FirstRazorApp/ViewComponents/HeadCountViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FirstRazorApp.AppRepository;
using FirstRazorApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FirstRazorApp.ViewComponents
{
    public class HeadCountViewComponent : ViewComponent
    {
        private readonly IEmpoyeeRepository _empoyeeRepository;

        public HeadCountViewComponent(IEmpoyeeRepository empoyeeRepository)
        {
            _empoyeeRepository = empoyeeRepository;
        }

        public IViewComponentResult Invoke(Dept? department = null)
        {
            var result = _empoyeeRepository.EmployeeCountByDept(department);
            return View(result);
        }
    }
}

FirstRazorApp/Pages/Employeers/Delete.cshtml
@page "{id}"
@model FirstRazorApp.Pages.Employeers.DeleteModel
@{
    ViewData["Title"] = "Delete";
    ViewData["ShowButtons"] = false;
}

<h1 class="text-center">Delete Confirmation</h1>
<div class="alert alert-danger">
    <div class="row">
        <div class="col-12 col-md-6 col-xl-4 offset-sm-0 offset-md-3 offset-xl-4">
            <partial name="_DisplayEmployeePartial" model="Model.Employee" view-data="ViewData" />
        </div>
    </div>
        <div class="row">
            <div class="col-12 col-md-6 col-xl-4 offset-sm-0 offset-md-3 offset-xl-4">
                <div class="text-center text-secondary">
                    <hr />
                    <h4>Employee ID: <span class="text-primary">@Model.Employee.Id</span></h4><hr />
                    <h4>Employee E-Mail: <span class="text-primary">@Model.Employee.Email</span></h4><hr />
                    <h4>Department: <span class="text-primary">@Model.Employee.Department</span></h4><hr />
                </div>
            </div>
        </div>
        <div class="row">
        <div class="col text-center">

            <h5>Are you sure want to delete employee - @Model.Employee.Name ?</h5>
            <form method="post">
                <button type="submit" class="btn btn-danger">Yes</button>
                <a class="btn btn-success" asp-page="/Employeers/Index">No</a>
            </form>
        </div>
    </div>
</div>

FirstRazorApp/Pages/Employeers/Details.cshtml
@*@page "/view/{id:even}"*@
@page "{id}"
@model FirstRazorApp.Pages.Employeers.DetailsModel
@{
    ViewData["Title"] = "Employee Details";
    var photoPath = $"~/images/{Model.Employee.PotoPath ?? "noimage.png"}";
}
<!--Второй способ передать параметр через page-->

<div class="row justify-content-center m-3">
    <div class="col col-lg-8">
        <div class="card cardBoxShadow">
            <div class="card-header cardHeaderStyle">
                <h1>@Model.Employee.Name</h1>
            </div>
            <div class="card-body cardBodyStyle text-center">
                <div class="row">
                    <div class="col col-lg-9">
                        <h4 class="cardTextLeftFloating">Employee ID: @Model.Employee.Id</h4><hr />
                        <h4 class="cardTextLeftFloating">Email: @Model.Employee.Email</h4><hr />
                        <h4 class="cardTextLeftFloating">Department: <span class="text-danger font-weight-bold">@Model.Employee.Department</span></h4>
                    </div>
                    <div class="col col-lg-3">
                        <div style="border-right: 1px solid rgba(0,0,0,.1);">
                            <img class="card-img-top imageThumbnail border border-primary" style="background-color: #d1e7ff;" src="@photoPath" asp-append-version="true" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="card-footer text-center" style="background-color: rgba(0, 0, 0, 0.25);">
                            <a asp-page="index" class="btn btn-success buttonShadow">Back</a>
                            <a asp-page="/Employeers/Edit" asp-route-ID="@Model.Employee.Id" class="btn btn-primary m-1 buttonShadow">Edit</a>
                            <a asp-page="/Employeers/Delete" asp-route-ID="@Model.Employee.Id" class="btn btn-danger m-1 buttonShadow">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col text-center">
        @*@await Component.InvokeAsync("HeadCount", new { department = Model.Employee.Department })*@
        <vc:head-count department="@Model.Employee.Department"></vc:head-count>
    </div>
</div>

FirstRazorApp/Pages/Employeers/Edit.cshtml
@page "{id:min(1)?}/{handler?}"
@model FirstRazorApp.Pages.Employeers.EditModel
@{
    string photoPath = $"/images/{Model.Employee.PotoPath ?? "noimage.png"}";
    string pageHeader = Model.Employee.Id > 0 ? $"Edit {Model.Employee.Name ?? "Unknown"} profile" : "Create";
    string buttonText = Model.Employee.Id > 0 ? "Update" : "Create";
    ViewData["Title"] = pageHeader;
}


@if (Model.Employee.Id > 0)
{
    <!--Добавляем поле с запросом об извещении об изменениях в профиле на е-маил-->
    <!--Вторая форма на странице-->
    <!--Хэлпер asp-page-handler="UpdateNotificationPreferences" явно указывает форме к какому методу обработки обращаться-->
    <form method="post" asp-page-handler="UpdateNotificationPreferences">
        <div class="row text-center notifyBlock">
            <div class="col form-check">
                <h1>Notification Preference</h1>
                <input asp-for="Notify" class="form-check-input"/>
                <label asp-for="Notify" class="form-check-label">
                    <p>Recive email notification when my details change</p>
                </label><br/>

                <button type="submit" class="btn btn-primary text-center">Update Notification Preferences</button>
                @if (!string.IsNullOrWhiteSpace(Model.Message))
                {
                    <p>
                        <div class="alert alert-success">
                            @Model.Message
                        </div>
                    </p>
                }
            </div>
        </div>
    </form>
    <hr/>
}

<h1 class="text-center">@pageHeader</h1>

<!--Вывод всех ошибок модели-->
<div asp-validation-summary="ModelOnly" class="text-danger text-center"></div>

<!--Создаём форму редактирования-->
<form method="post" class="mt-3" enctype="multipart/form-data" asp-page-handler="OnPost">
    <!--Создаём скрытое поле для параметра ID-->
    <input type="hidden" asp-for="Employee.Id" />

    <!--Создаём скрытое поле для параметра photoPath-->
    <input type="hidden" asp-for="Employee.PotoPath" />

    <!--Добавляем поля редактирования-->
    <div class="row justify-content-center m-3">
        <div class="col col-lg-8">
            <div class="card cardBoxShadow">
                <div class="card-header cardHeaderStyle text-center">
                    <!--Добавляем поле редактирования имени-->
                    <div class="form-group row">
                        <label asp-for="Employee.Name" class="col col-lg-4 col-form-label text-right">Edit Name:</label>
                        <div class="col col-lg-6">
                            <input asp-for="Employee.Name" class="form-control" placeholder="@Model.Employee.Name" />
                            <!--Добавляем сообщение валидации формы-->
                            <span asp-validation-for="Employee.Name" class="text-danger"></span>
                        </div>
                    </div>

                </div>
                <div class="card-body cardBodyStyle text-center">
                    <div class="row">
                        <div class="col col-lg-9">
                            <h4 class="cardTextLeftFloating">Employee ID: @Model.Employee.Id</h4><hr />

                            <!--Добавляем поле редактирования e-mail-->
                            <div class="form-group row">
                                <label asp-for="Employee.Email" class="col col-lg-4 col-form-label text-right">Edit E-mail:</label>
                                <div class="col-12 col-lg-6">
                                    <input asp-for="Employee.Email" class="form-control mr-2" placeholder="@Model.Employee.Email" />
                                    <!--Добавляем сообщение валидации формы-->
                                    <span asp-validation-for="Employee.Email" class="text-danger"></span>
                                </div>
                            </div>
                            <hr />
                            <!--Добавляем поле редактирования департамента-->
                            <div class="form-group row">
                                <label asp-for="Employee.Department" class="col col-lg-4 col-form-label text-right">Edit Department:</label>
                                <div class="col-12 col-lg-6">
                                    <!--Создаём выпадающий список с департаментами-->
                                    <!--Необходимо подключить класс локально или глобально-->
                                    <select asp-for="Employee.Department" class="custom-select mr-2" asp-items="Html.GetEnumSelectList<Dept>()">
                                        <!--Добавляем начальный элемент выпадающего списка-->
                                        <option value="">Please Select</option>
                                    </select>
                                    <span asp-validation-for="Employee.Department" class="text-danger"></span>
                                </div>
                            </div>
                            <hr />
                        </div>
                        <div class="col col-lg-3">
                            <div style="border-right: 1px solid rgba(0,0,0,.1);">
                                <img class="card-img-top imageThumbnail border border-primary" style="background-color: #d1e7ff;" src="@photoPath" asp-append-version="true" />
                                <!--Добавляем редактирование изображения-->

                                <div class="custom-file">
                                    <input asp-for="Photo" class="custom-file-input form-control" />
                                    <label class="custom-file-label text-left"></label>
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="card-footer text-center" style="background-color: rgba(0, 0, 0, 0.25);">
                                <a asp-page="index" class="btn btn-primary buttonShadow">Cancel</a>
                                <button type="submit" class="btn btn-success m-1 buttonShadow">@buttonText</button>
                                <a asp-page="/Employeers/Delete" asp-route-ID="@Model.Employee.Id" class="btn btn-danger m-1 buttonShadow">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {

    <script src="~/js/UploadBoxTextScript.js"></script>
    <partial name="_ValidationScriptsPartial" />
}

FirstRazorApp/Pages/Employeers/EmpCount.cshtml
@page
@model FirstRazorApp.Pages.Employeers.EmpCountModel
@{
    ViewData["Title"] = "EmpCount";
}

<h1>All departments head count</h1>
<h6>Form without parameter</h6>
@*@await Component.InvokeAsync("HeadCount")*@
<vc:head-count department="@null"></vc:head-count>

<!--Вывод формы с параметром-->
<h1>Only IT department head count</h1>
<h6>Form with parameter</h6>
@await Component.InvokeAsync("HeadCount", new { department = Dept.It })

FirstRazorApp/Pages/Employeers/Index.cshtml
@page
@model FirstRazorApp.Pages.Employeers.IndexModel
@{
    ViewData["Title"] = "Employees";
    ViewData["ShowButtons"] = true;
}

<h1 class="text-center">Employees: @Model.Employees.Count()</h1>
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success text-center">@TempData["SuccessMessage"]</div>
}

<!--Форма поиска персонала-->
<form method="get">
    <div class="input-group">
        <input class="form-control" asp-for="SearchTerm" />
        <div class="input-group-append">
            <button class="btn btn-primary">Search</button>
        </div>
    </div>
</form>

<div class="row">

    @foreach (var item in Model.Employees)
    {
        <div class="col-12 col-sm-6 col-lg-4">
            <partial name="_DisplayEmployeePartial" model="item" view-data="ViewData" />
        </div>
    }

</div>